 PIC EQU 20H
 IMR EQU 21H
 TIMER EQU 10H
 COMP EQU 11H
 INT0 EQU 24H
 INT1 EQU 25H


ORG 20
 DW RUT_F10         ;RUT F10 EN LA DIR 3000H

ORG 24
 DW RUT_TIMER         ;RUT TIMER EN LA DIR 3000H

ORG 1000H
 CONT DB 30H, 30H
 SALTO DB 0AH


ORG 2000H
 CLI
 MOV AL, 11111110B
 OUT IMR, AL      ;F10 ACTIVADO
 MOV AL, 1
 OUT COMP, AL     ;COMPARA CON 1SEG
 MOV AL, 5
 OUT INT0, AL     ;F10 EN LA DIR 5*4=20
 MOV AL, 6
 OUT INT1, AL     ;TIMER EN LA DIR 6*4=24
 STI
LOOP: JMP LOOP



RUT_F10:PUSH AX
 IN AL, IMR
 XOR AL, 00000010B  ;SI ESTA ANDANDO (BIT1=0) LO DESACTIVA, SINO LO ACTIVA
 OUT IMR, AL
 MOV AL, PIC
 OUT PIC, AL
 MOV AL, 0
 OUT TIMER, AL    ;CONTADOR EN 0
 POP AX
 IRET


RUT_TIMER:PUSH AX
 MOV BX, OFFSET CONT+1
 CMP BYTE PTR [BX], 39H
 JZ AUMENTARC2
 INC BYTE PTR [BX]
 JMP PRINT

AUMENTARC2:MOV BYTE PTR [BX], 30H
 DEC BX
 CMP BYTE PTR [BX], 32H
 JZ TERMINO
 INC BYTE PTR [BX]

PRINT:MOV BX, OFFSET CONT
 MOV AL, OFFSET SALTO-OFFSET CONT
 INT 7
 MOV AL, PIC
 OUT PIC, AL
 MOV AL, 0
 OUT TIMER, AL
 POP AX
 IRET
TERMINO:HLT
END
